const LegendaryBirds = [
    {
        'name': 'Articuno',
        'image': 'https://archives.bulbagarden.net/media/upload/thumb/4/4e/144Articuno.png/375px-144Articuno.png',
        'sprite': 'https://img.pokemondb.net/sprites/sword-shield/normal/articuno.png',
        'biology': 'Articuno is a large avian Pokémon with predominantly sky blue plumage and wings said to be made of ice. On its forehead is a crest that consists of three, darker blue rhombus-shaped feathers. It has circular red eyes, a short gray beak, and long, thin gray legs. Each foot has three forward-facing toes and one that faces backward. On its chest is a mass of pale blue, downy feathers. Its long, streamer-like tail is longer than its body and the same shade of blue as its crest. Articuno has the power to control the ice at will. When Articuno flaps its wings, it can chill the moisture in the air around it, making snow fall. It flies from icy mountain to icy mountain. According to legend, it appears before doomed travelers lost in icy regions. As seen in the anime, Articuno sometimes aids travelers and guides them to safety. Articuno lives in cold, isolated locations such as snowy mountains filled with permafrost.In Galar, Articuno has a distinct appearance. The main body has lavender coloration with a black marking covering its chest. Its feet are black with lavender talons. The three feathers of its crest, which are longer, fused, and folded to the back, have the same purple color as its beak and tail. Its eyes glow light blue, appear to be mostly closed, and are surrounded by a black, mask-like facial disc. When Articuno utilizes its psychic power, the entire mask glows the same color as its eyes, as do the white, feather-like blades of condensed psychic power at the edges of its wings.',
        'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Pok%C3%A9mon_Ice_Type_Icon.svg/1024px-Pok%C3%A9mon_Ice_Type_Icon.svg.png',
        'bg_color': '#8FCBFF',
        'btn_color': '#54A8F2'
    },
    {
        'name': 'Zapdos',
        'image': 'https://images.wikidexcdn.net/mwuploads/wikidex/thumb/d/d8/latest/20160316194916/Zapdos.png/300px-Zapdos.png',
        'sprite': 'https://img.pokemondb.net/sprites/sword-shield/normal/zapdos.png',
        'biology': 'Zapdos is a large, avian Pokémon with predominantly yellow plumage. It has small, triangular eyes with black around them and a long, thin, light orange beak. Its wings and tail are a mass of spiky feathers and there are black feathers covering the back of its wings and inner tail feathers. A large crest of spiked feathers surrounds its head. Its thighs are tan, and it has thin, light orange legs. It has feet with three forward-facing toes and one backward-facing toe; each toe has a short talon. When Zapdos flaps its glittering wings, it releases electricity that can potentially cause thunderstorms. It produces massive crackling and snapping sounds when it flies; these are attributed to the lightning bolts it sheds when airborne. Zapdos reportedly appears only during thunderstorms and gains power when struck by lightning. It is said to live among thunderclouds, but it is rarely seen. In Galar, Zapdos has a different appearance. The main body is red-orange with black plumage. Its head features yellow eyes with more pronounced, mask-like black coloration around them, a shorter black beak, and a longer, more visible neck. Its legs are black, longer, and more muscular, its thigh feathers are also black, and its talons are yellow with red rings at their bases. Its red-orange wings are smaller, with small black markings that appear to be remnants of its Kantonian counterparts black plumage. Finally, it has a row of spiky feathers along its chest, and a similar row of black feathers on its back.',
        'icon' : 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Pok%C3%A9mon_Electric_Type_Icon.svg/2048px-Pok%C3%A9mon_Electric_Type_Icon.svg.png',
        'bg_color': '#EBF75B',
        'btn_color': '#000'
    },
    {
        'name': 'Moltres',
        'image': 'https://archives.bulbagarden.net/media/upload/thumb/1/1b/146Moltres.png/375px-146Moltres.png',
        'sprite': 'https://img.pokemondb.net/sprites/sword-shield/normal/moltres.png',
        'biology': ' Moltres is a large, avian Pokémon with golden plumage. It has a long, flowing head crest and a billowing tail, both made of reddish-orange and yellow flames. Additionally, its wings are also shrouded in fiery plumage. When using its the wings, they gain a dazzling red glow. It has a long, thin neck, a pointed, brown beak, and small, triangular eyes. Its thin, brown legs have feet that have three forward-facing toes and one backward-facing toe. It has short talons. Moltres sheds embers with every flap of its wings, creating a brilliant flash of flames. By dipping itself into the magma of an active volcano, this Pokémon can heal itself. It migrates to the south with the coming of spring and is said to bring an early springtime to cold lands. There have been stories of Moltres using its wings to assist those lost in the mountains. Moltres is rarely seen. In the past, Sky Attack was its signature move.In Galar, Moltres has a similar build, but a drastically different color scheme. Its body is primarily black with scarlet highlights and bright blue eyes. Its scarlet beak is hooked at the tip and leads to markings that run down its front and behind its head. Its feet are also scarlet with black talons. Its wings, crest, and tail are mostly black, with the crest having an extra curl at the front and the tail being split in two, and all three of these features exude a magenta, flame-like energy that earns it the name of its Kantonian counterpart. The sinister energy that blazes from within its body is so oppressive that most Pokémon cant even approach it. Galarian Moltres attacks by spreading its wings wide to unleash its energy in a powerful aura that attacks the minds of its foes, inflicting deep fatigue as it burns away their energy from within. The aura has the power to consume the spirit of its victims, reducing them to burned-out shadows of themselves. It is said to have a haughty personality and a calm demeanor. It appears in the Crown Tundra once every few decades to reach Dyna Tree Hill. Galarian Moltres is the only Pokémon that can learn the move Fiery Wrath.',
        'icon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Pok%C3%A9mon_Fire_Type_Icon.svg/768px-Pok%C3%A9mon_Fire_Type_Icon.svg.png',
        'bg_color': '#F08730',
        'btn_color': '#F04D30'
    },

]

export {LegendaryBirds};